<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="\Practice\mvc\skin\image\logo\favicon.png">
    <title>Product Info</title>
    <?php echo ($this->getChild('head')->toHtml()); ?>
</head>

<body>
    <div>
        <?php echo ($this->getChildHtml('header')); ?>
    </div>
    
    <div>
        <?php echo ($this->getChildHtml('messages')); ?>
    </div>

    <div>
        <?php echo ($this->getChildHtml('content')); ?>
    </div>

    <div>
        <?php echo ($this->getChildHtml('footer')); ?>
    </div>
    
</body>

</html>