<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Product Information</title>
    <?php echo ($this->getChild('head')->toHtml()); ?>
</head>

<body>
    <div>
        <?php echo ($this->getChildHtml('header')); ?>
    </div>
    
    <div>
        <?php echo ($this->getChildHtml('messages')); ?>
    </div>

    <div>
        <?php echo ($this->getChildHtml('content')); ?>
    </div>

    <div>
        <?php echo ($this->getChildHtml('footer')); ?>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>

</html>