<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="<?php echo Mage::getBaseUrl().'/skin/image/logo/favicon.png' ?>">
    <title>Admin</title>
    <?php echo ($this->getChild('head')->toHtml()); ?>
</head>

<body>
    <div>
        <?php echo ($this->getChildHtml('header')); ?>
    </div>
    
    <div style="min-height:73.3vh">
        <?php echo ($this->getChildHtml('content')); ?>
    </div>

    <div>
        <?php echo ($this->getChildHtml('footer')); ?>
    </div>
    
</body>

</html>