<div class="container">
    <div class="customer-details-card">
        <?php $customer = $this->getCustomerDetails(); ?>
        <h2>Customer Details</h2>
        <p><strong>Customer ID:<?php echo $customer->getId() ?></strong></p>
        <p><strong>Email:</strong><?php echo $customer->getCustomerEmail() ?></p>
        <p><strong>Name:</strong> <?php echo ucfirst($customer->getFirstName()). ' '. ucfirst($customer->getLastName()) ?></p>
    </div>

    <div class="main-content">
        <div class="sidebar">
            <div class="toggle-button" id="address-toggle">Address Details</div>
            <div class="address-details card">
                <?php $address = $this->getAddressDetails() ?>
                <h2>Billing Address</h2>
                <p><strong>Address:</strong><?php echo $address->getBillingAddress() ?></p>
                <p><strong>City:</strong><?php echo $address->getBillingCity() ?></p>
                <p><strong>Region:</strong><?php echo $address->getBillingRegion() ?></p>
                <p><strong>Country:</strong><?php echo $address->getBillingCountry() ?></p>
                <p><strong>Phone:</strong><?php echo $address->getBillingPhone() ?></p>
                <h2>Shipping Address</h2>
                <p><strong>Address:</strong><?php echo $address->getShippingAddress() ?></p>
                <p><strong>City:</strong> <?php echo $address->getShippingCity() ?></p>
                <p><strong>Region:</strong> <?php echo $address->getShippingRegion() ?></p>
                <p><strong>Country:</strong> <?php echo $address->getShippingCountry() ?></p>
                <p><strong>Phone:</strong> <?php echo $address->getShippingPhone() ?></p>
            </div>

            <div class="toggle-button" id="shipping-toggle">Shipping Details</div>
            <div class="shipping-details card">
                <?php $shipping = $this->getShippingDetails(); ?>
                <h2>Shipping Details</h2>
                <p><strong>Shipping Id:</strong> <?php echo $shipping->getId() ?></p>
                <p><strong>Shipping Method:</strong> <?php echo ucwords(str_replace('_',' ', $shipping->getShippingMethod())) ?></p>
            </div>

            <div class="toggle-button" id="payment-toggle">Payment Details</div>
            <div class="payment-details card">
                <?php $payment = $this->getPaymentDetails(); ?>
                <h2>Payment Details</h2>
                <p><strong>Payment ID:</strong><?php echo $payment->getId() ?></p>
                <p><strong>Payment Method:</strong> <?php echo ucwords(str_replace('_',' ', $payment->getPaymentMethod())) ?></p>
                <p><strong>Card Number:</strong> <?php echo $payment->getCardNumber() ?></p>
            </div>
        </div>

        <div class="products card">
            <h2> Purchased Products</h2>
            <?php $order = $this->getOrderDetails(); ?>
            <h3>Order Number: <?php echo $order->getOrderNumber() ?></h3>
            <h3 class="status" >Status: <?php echo ucwords(str_replace('_', ' ', $order->getStatus())) ?>
                <?php $orderStatus = $order->getStatus(); ?>
                <form class="status-update-form" action="<?php echo $this->getUrl('admin/sales_order/save') ?>" method="post">
                    <input type="hidden" value="<?php echo $order->getId(); ?>" name="order[order_id]" >
                    <div class="form-field">
                        <label for="status">Status:</label>
                        <select name="order[status]" >
                            <option value="pending" <?php if($orderStatus=="pending"){echo 'selected';} ?> >Pending</option>
                            <option value="confirmed" <?php if($orderStatus=="confirmed"){echo 'selected';} ?>>Confirmed</option>
                            <option value="shipped" <?php if($orderStatus=="shipped"){echo 'selected';} ?>>Shipped</option>
                            <option value="out_for_delivery" <?php if($orderStatus=="out_for_delivery"){echo 'selected';} ?>>Out For Delivery</option>
                            <option value="delivered" <?php if($orderStatus=="delivered"){echo 'selected';} ?>>Delivered</option>
                            <option value="canceled" <?php if($orderStatus=="canceled"){echo 'selected';} ?>>Canceled</option>
                            <option value="declined" <?php if($orderStatus=="declined"){echo 'selected';} ?>>Declined</option>
                            <option value="refunded" <?php if($orderStatus=="refunded"){echo 'selected';} ?>>Refunded</option>
                        </select>
                    </div>
                    <div class="form-field">
                        <button class="primary-button" type="submit">Update Status</button>
                    </div>
                </form>
            </h3>
            <div class="order-items">
                <?php foreach($this->getOrderItems() as $item): ?> 
                <?php $product = $item->getProduct() ?> 
                    <div class="product">
                        <img src="<?php echo $this->getUrl('media/product/'. $product->getImageLink())  ?>" alt="Product Img">
                        <div>
                            <p><strong>SKU:</strong><?php echo $product->getSku() ?></p>
                            <p><strong>Product Name:</strong><?php echo $item->getProductName() ?></p>
                            <p><strong>Quantity:</strong><?php echo $item->getQty() ?></p>
                            <p><strong>Price:</strong><?php echo $item->getPrice() ?></p>
                            <p><strong>Row Total:</strong><?php echo $item->getRowTotal() ?></p>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>

<script>
    function initializeToggleButtons() {
        console.log("Initializing toggle buttons...");
        document.getElementById('shipping-toggle').addEventListener('click', function() {
            toggleDetails('shipping-details');
        });

        document.getElementById('address-toggle').addEventListener('click', function() {
            toggleDetails('address-details');
        });

        document.getElementById('payment-toggle').addEventListener('click', function() {
            toggleDetails('payment-details');
        });
    }

    function toggleDetails(className) {
        var details = document.querySelector('.' + className);
        var allDetails = document.querySelectorAll('.shipping-details, .address-details, .payment-details');

        var isOpen = details.style.display !== 'none';

        allDetails.forEach(function(item) {
            item.style.display = 'none';
        });

        if (!isOpen) {
            details.style.display = 'block';
        }
    }

    initializeToggleButtons();
</script>