<?php 
    $order = $this->getOrderDetails();
?>

<div class="container" >
    <form action="<?php echo $this->getUrl('sales/admin_orders/save') ?>" method="post">
        <div class="form-field">
            <label for="order_number">Order Number:</label>
            <input type="text" id="order_number" name="order_number" value="<?php echo $order->getOrderNumber() ?>" readonly>
        </div>
        
        <div class="form-field">
            <label for="status">Status:</label>
            <select id="status" name="status" >
                <option value="pending">Pending</option>
                <option value="shipped">Shipped</option>
                <option value="cancel">Cancel</option>
                <option value="declined">Declined</option>
                <option value="refunded">Refunded</option>
                <option value="delivered">Delivered</option>
            </select>
        </div>
        <div class="form-field">
            <button type="submit">Update Status</button>
        </div>
    </form>

</div>