<div class="login-container">
    <form class="login-form" method="post" action="<?php echo $this->getUrl('admin/user/login') ?>" >
        <h2>Admin Login</h2>
        <div class="form-field">
            <label for="email">Email:</label>
            <input type="email" id="email" name="login[email]" required>
        </div>
        <div class="form-field">
            <label for="password">Password:</label>
            <input type="password" id="password" name="login[password]" required>
        </div>
        <div class="form-action">
            <button type="submit">Login</button>
        </div>
    </form>
</div>