<div class="product-container">
    <?php $products = $this->getCategory()->getdata(); ?>

    <?php foreach ($products as $product): ?>
        <div class="product-card">
            <img src="<?php echo Mage::getBaseUrl('media/product/'. $product->getImageLink() ) ?>" alt="Product Image" class="product-image">
            <h3 class="product-title"><?php echo $product->getName(); ?></h3>
            <p class="product-description"><?php echo $product->getDescription(); ?></p>
            <span class="product-price"><?php echo $product->getPrice(); ?></span>
            <button class="add-to-cart"><a href="<?php echo Mage::getBaseUrl('catalog/product/view?id='.$product->getProductId())?>">View</a></button>
        </div>
    <?php endforeach; ?>
</div>
