<div class="form">
    <h2>Category Form</h2>
    <form method="POST" action="<?php echo $this->getUrl('/catalog/category/save') ?>">
        <div class="">
            <input type="hidden" name="catalog_category[category_id]">
        </div>
        <div class="">
            <label for="category_name">Category Name:</label>
            <input type="text" name="catalog_category[category_name]" id="category_name">
        </div>
        <div class="">
            <label for="status">Status:</label>
            <input type="text" name="catalog_category[status]" id="status">
        </div>
        <div class="">
            <input type="submit" name="submit" value="Submit">
        </div>
    </form>
</div>