<h2 class="title" >Orders</h2>
<div class="orderbox">
    <?php foreach ($this->getAllOrders() as $order) :?>    
        <?php foreach ($this->getOrderedProduct($order->getOrderId()) as $item) :?>
            <div class="order-card">
                <img class="product-image" src="<?php echo Mage::getBaseUrl('media/product/'. $this->getProductImage($item->getProductId())); ?>" alt="Product Image">
                <div class="order-details">
                    <p class="product-name"><?php echo $item->getProductName() ?></p>
                    <p class="color">Color: <span class="color-box" style="background-color: <?php echo $item->getProductColor(); ?>;"></span></p>
                    <p class="quantity">Quantity: <?php echo $item->getQty() ?></p>
                    <p class="total">Total: <?php echo $item->getRowTotal() ?></p>
                    <p>Status: <?php echo $this->getOrderStatus($order->getOrderId())?></p>
                    <div class="progress-bar-container">
                        <div class="progress-bar" data-status="<?php echo $this->getOrderStatus($order->getOrderId()); ?>"></div>
                    </div>
                    <?php $status = $this->getOrderStatus($order->getOrderId()); ?>
                    <?php if ($status == 'pending' || $status == 'confirmed' || $status == 'shipped'): ?>
                        <form action="<?php echo $this->getUrl('sales/customer_orders/cancel') ?>" method="post">
                            <input type="hidden" value="<?php echo $order->getOrderId()?>" name="cancel[order_id]">
                            <input type="hidden" value="cancel" name="cancel[to_status]">
                            <input type="submit" value="Cancel" class="cancel-button">
                        </form>
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach;?>     
    <?php endforeach;?> 
</div>


<script>
function calculateWidth(status) {
    switch (status) {
        case 'pending':
            return 10; 
        case 'confirmed':
            return 30;
        case 'shipped':
            return 50; 
        case 'delivered':
            return 100;
        default:
            return 0; 
    }
}
var progressBarContainers = document.querySelectorAll('.progress-bar-container');

function updateProgressBars() {
    progressBarContainers.forEach(function (container) {
        var progressBar = container.querySelector('.progress-bar');
        var status = progressBar.getAttribute('data-status');
        var width = calculateWidth(status);
        progressBar.style.width = width + '%';
    });
}

updateProgressBars();
</script>