<div class="login-container">
    <form class="login-form" method="post" action="<?php echo $this->getUrl('admin/import/save') ?>" enctype="multipart/form-data">
        <h2>Upload File</h2>
        <div class="form-field">
            <label for="upload">Upload Csv:</label>
            <input type="file"  name="csvfile"  id="upload" required >
        </div>
        <div class="form-action">
            <button type="submit">Upload</button>
        </div>
    </form>

    <button class="button2" ><a href="<?php echo $this->getUrl('admin/import/read') ?>">Read</a></button>
    <button class="button2"><a href="<?php echo $this->getUrl('admin/import/import') ?>">Import</a></button>
</div>


