<div class="login-container">
    <form class="login-form" method="post" action="<?php echo $this->getUrl('admin/import/save') ?>" enctype="multipart/form-data">
        <h2>Upload File</h2>
        <div class="form-field">
            <label for="upload">Upload Csv:</label>
            <input type="file"  name="csvfile"  id="upload" required >
        </div>
        <div class="form-action">
            <button class="upload-button" type="submit">Upload</button>
        </div>
    </form>
</div>

<div class="table-container">
    <h2 class="table-heading">List</h2>
    <table>
        <thead>
            <tr>
                <th>File</th>
                <th colspan="2">Actions</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->getFileList() as $file): ?>
                <tr>
                    <td>
                        <?php echo $file ?>
                    </td>
                    <td>
                        <a href="<?php echo $this->getUrl('admin/import/read?filename='.$file) ?>">Read</a>
                    </td>
                    <td>
                        <a href="<?php echo $this->getUrl('admin/import/import') ?>">Import</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>


