<div class="login-container">
<form class="login-form" method="post" action="<?php echo $this->getUrl('tempconverter/converter/save') ?>" >
        <h2>Convert</h2>
        <div class="form-field">
            <input type="hidden" id="id" name="tempdata[id]" >
        </div>
        <div class="form-field">
            <label for="username">Username:</label>
            <input type="text" id="username" name="tempdata[user_name]" >
        </div>
        <div class="form-field">
            <label for="tempreature">Tempreature:</label>
            <input type="float" id="tempreature" name="tempdata[temprature]" >
        </div>
        <div class="form-field">
            <label for="unit">Unit:</label>
            <select name="tempdata[unit]" id="unit">
                    <option value="Celcious" class="">Celcious</option>
                    <option value="Fahrenhit" class="">Fahrenhit</option>
                    <option value="Kelvin" class="">Kelvin</option>
            </select>
        </div>
        <div class="form-field">
            <label for="convert_unit">Convert Unit:</label>
            <select name="tempdata[convert_unit]" id="convert_unit">
                    <option value="Celcious" class="">Celcious</option>
                    <option value="Fahrenhit" class="">Fahrenhit</option>
                    <option value="Kelvin" class="">Kelvin</option>
            </select>
        </div>
        <div class="form-action">
            <button type="submit">Convert</button>
        </div>
    </form>
</div>
<div>

</div>