<header class="header">
    <a href="<?php echo Mage::getBaseUrl()?>" class="logo">
        <img src="<?php echo Mage::getBaseUrl().'/skin/image/logo/logo.png' ?>" alt="Logo">
        ShopNow
    </a>
    <button class="nav-toggle" aria-label="Toggle navigation">
        <span class="hamburger"></span>
    </button>
    <nav class="nav">
        <ul class="nav__list">
            <!-- <li class="nav__item"><a href="#" class="nav__link">Category</a></li> -->
            <li class="nav__item"><a href="#" class="nav__link">Cart</a></li>
            <li class="nav__item"><a href="#" class="nav__link">Customer care</a></li>
            <li class="nav__item ">
                <div class="logo">
                    <img src="<?php echo Mage::getBaseUrl().'/skin/image/logo/user.png' ?>" alt="User Image" class="user-image">
                    <span class="nav__username"><?php echo $this->getUser(); ?></span>
                </div>
            </li>
            <li class="nav__item"><a href="<?php echo Mage::getBaseUrl().'/customer/account/logout' ?>" class="nav__link login-button">Logout</a></li>
        </ul>
    </nav>
</header>