<header class="header">
    <a href="<?php echo Mage::getBaseUrl()?>" class="logo">
        <img src="<?php echo Mage::getBaseUrl().'/skin/image/logo/logo.png' ?>" alt="Logo">
        Shopnow
    </a>
    <button class="nav-toggle" aria-label="Toggle navigation">
        <span class="hamburger"></span>
    </button>
    <nav class="nav">
        <ul class="nav__list">
            <li class="nav__item"><a href="<?php echo Mage::getBaseUrl('admin/catalog_product/form')?>" class="nav__link">Add Product</a></li>
            <li class="nav__item"><a href="<?php echo Mage::getBaseUrl('admin/catalog_product/list')?>" class="nav__link">Product List</a></li>
            <li class="nav__item"><a href="<?php echo Mage::getBaseUrl('admin/catalog_category/form')?>" class="nav__link">Add Category</a></li>
            <li class="nav__item"><a href="<?php echo Mage::getBaseUrl('admin/catalog_category/list')?>" class="nav__link">Category List</a></li>
            <li class="nav__item"><a href="<?php echo Mage::getBaseUrl('admin/banner/form')?>" class="nav__link">Add Banner</a></li>
            <li class="nav__item"><a href="<?php echo Mage::getBaseUrl('admin/banner/list')?>" class="nav__link">Banner List</a></li>
            <li class="nav__item ">
                <div class="logo">
                    <img src="<?php echo Mage::getBaseUrl().'/skin/image/logo/user.png' ?>" alt="User Image" class="user-image">
                    <?php echo $this->getAdmin(); ?>
                </div>
            </li>
        </ul>
    </nav>
</header>