<div class="form-container">
    <form method="post" action="<?php echo $this->getUrl('customer/account/forgotpassword') ?>" class="forget-password-form">
        <h2>Forget Password</h2>
        <div class="form-field">
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>
        </div>
        <div class="form-action">
            <button type="submit">Reset Password</button>
        </div>
    </form>
    <div class="login-links">
        <a href="<?php echo $this->getUrl('customer/account/login') ?>">Login ?</a>
    </div>
</div>