<div class="login-container">
    <form class="login-form" method="post" action="<?php echo $this->getUrl('customer/account/login') ?>" >
        <h2>Login</h2>
        <div class="form-field">
            <label for="email">Email:</label>
            <input type="email" id="email" name="login[email]" required>
        </div>
        <div class="form-field">
            <label for="password">Password:</label>
            <input type="password" id="password" name="login[password]" required>
        </div>
        <div class="form-action">
            <button type="submit">Login</button>
        </div>
    </form>
    <div class="login-links">
        <p><a href="<?php echo $this->getUrl('customer/account/forgotpassword') ?>">Forgot password ?</a></p>
        <a href="<?php echo $this->getUrl('customer/account/register') ?>">Register ?</a>
    </div>
</div>